package view.responses;

public enum CardEffectsResponses {
    INVALID_CELL_NUMBER,
    PLEASE_SELECT_A_VALID_NUMBER,
    PLEASE_SELECT_MONSTER,
    PLEASE_SELECT_A_VALID_MONSTER,
    DO_YOU_WANT_TO_SPECIAL_SUMMON,
    PLEASE_SELECT_LEVEL_7_OR_MORE,
    PLEASE_SELECT_LEVEL_4_OR_LESS,
    MONSTER_ZONE_IS_FULL,
    PLEASE_SELECT_AN_SPELL,
    PLEASE_SELECT_A_FIELD_SPELL,
    NO_FIELD_ZONE_SPELL_FOUND,
    PLEASE_SELECT_A_VALID_TYPE,
    YOU_DONT_HAVE_ANY_FIELD_SPELL,
}
