package view.responses;

public enum GameMenuResponses {
    INVALID_SELECTION,
    NO_CARD_FOUND,
    SUCCESSFUL,
    CARD_IS_HIDDEN,
    NO_CARD_IS_SELECTED,
    SPELL_ZONE_IS_FULL,
    MONSTER_ZONE_IS_FULL,
    NOT_ENOUGH_MONSTERS,
    THIS_CARD_CANT_NORMAL_SUMMON,

}
