package view.responses;

public enum GameMenuResponses {
    INVALID_SELECTION,
    NO_CARD_FOUND,
    SUCCESSFUL,
    CARD_IS_HIDDEN,
    SPELL_ZONE_IS_FULL,
    MONSTER_ZONE_IS_FULL,
    NOT_ENOUGH_MONSTERS,
    THIS_CARD_CANT_NORMAL_SUMMON,
    CANT_ATTACK,
    ALREADY_SUMMONED,
    NO_MONSTER_ON_THIS_ADDRESS,
    YOU_HAVENT_SUMMONED_YET,
    ALREADY_IN_THIS_POSITION,
    CANT_FLIP_SUMMON,
    ALREADY_ATTACKED,
    PLEASE_SELECT_MONSTER,
    PLEASE_SELECT_SPELL_OR_TRAP,
    CANT_RITUAL_SUMMON,
    SELECTED_LEVELS_DONT_MATCH,
    SELECTED_MONSTER_IS_NOT_RITUAL,
    NO_RITUAL_SPELL_IN_SPELLZONE,

}
