package view.responses;

public enum ThreeRoundGameResponses {
    INVALID_COMMAND,
    CHOSE_A_VALID_DECK,
    CARD_WITH_THIS_NAME_DOES_NOT_EXIST_IN_MAIN_DECK,
    CARD_WITH_THIS_NAME_DOES_NOT_EXIST_IN_SIDE_DECK,
    YOU_DONT_HAVE_DECK_WITH_THIS_NAME,

}
