package model.card;

public enum CardFeatures {
    NORMAL_SUMMON,
    SPECIAL_SUMMON,
    RITUAL_SUMMON,
    SUMMON_EFFECT,
    FLIP_EFFECT,
    CANT_ATTACK_WHEN_FACE_UP,
    CHANGING_ATK_DEF_POINTS_OF_CARDS,
    DESTROY_ATTACKER,
    MAKE_ATTACKER_ZERO,
    ONE_EFFECT_PER_ROUND,
    USED_EFFECT,
    SCANNER,
    CANT_DESTROY_IN_ATTACK,
    STOP_ATTACK,
    VARIABLE_ATK_DEF_NUMBERS,
    BANNING_TRAPS,
    HAS_SPECIAL_SUMMON_AFTER_NORMAL_SUMMON,
    HAS_SPECIAL_SUMMON_AFTER_DEFENDING,
    HAS_SPECIAL_NORMAL_SUMMON,

}
