package model;

public enum EffectLimitations {
    CANT_ACTIVATE_TRAP,
    PLAYER1_CANT_ATTACK,
    PLAYER2_CANT_ATTACK,
    PLAYER2_CANT_ATTACK_MORE_THAN_1500,
    PLAYER1_CANT_ATTACK_MORE_THAN_1500,
    SPELL_CASTER_PLUS_200,
    FIEND_PLUS_200,
    FAIRY_MINUS_200,
    BEAST_PLUS_200,
    WARRIOR_PLUS_200,
    BEAST_WARRIOR_PLUS_200,
    BEAST_TYPE_ATK_PLUS_GRAVEYARD_TIMES_100,
    AQUA_ATK_PLUS_500,
    AQUA_DEF_MINUS_400,
    FIEND_PLUS_ATK_400,
    FIEND_MINUS_DEF_200,
    SPELL_CASTER_MINUS_DEF_200,
    SPELL_CASTER_PLUS_ATK_400,
    HAS_DRAW_PHASE,
}
